apiVersion: v1
kind: Secret
metadata:
  name: postgresql
stringData:
  creds.json: |
    {
      "host": "postgres.postgres.svc.cluster.local",
      "port": "5432",
      "user": "postgres",
      "password": "admin",
      "dbname": "orders"
    }
